#! /bin/bash

# dobiva argumenti N: 1:ime.py zbor_za_prebaruvanje lista_datoteki

if [[ $1 == *.py ]]; then
    # 1) vidi dali postoe
    if [ -f "$1" ]; then
        echo "$(python3 "$1" "${@:2}")"
        exit 0
    else
        echo "File $1 not found!"
        exit 1
    fi

else 
    # 1.2) dokolku nema py file u cmd line zemi osnoven prv.py file 
    file="prva.py"
    
    if [ -f "$file" ]; then
        echo "$(python3 "$file" "${@:}")"
    else
        echo "No 'prva.py' found!"
        exit 1
    fi
fi



